// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEk-UB8YmJaxLr566NpYVk3UrzbdInivA',
    appId: '1:476678681450:web:312dfbdc7933fe8722ab13',
    messagingSenderId: '476678681450',
    projectId: 'my-recipes-28341907',
    authDomain: 'my-recipes-28341907.firebaseapp.com',
    storageBucket: 'my-recipes-28341907.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd0IR13NJhcdFK0LOZlEX14II0vmLaIHc',
    appId: '1:476678681450:android:b03f1b95b2bc833122ab13',
    messagingSenderId: '476678681450',
    projectId: 'my-recipes-28341907',
    storageBucket: 'my-recipes-28341907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopgqn4r-0zuIrNwkRtHT9FGV4svWk2i0',
    appId: '1:476678681450:ios:05a86a81a40f293022ab13',
    messagingSenderId: '476678681450',
    projectId: 'my-recipes-28341907',
    storageBucket: 'my-recipes-28341907.appspot.com',
    iosBundleId: 'com.example.myRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCopgqn4r-0zuIrNwkRtHT9FGV4svWk2i0',
    appId: '1:476678681450:ios:314a2470542e753822ab13',
    messagingSenderId: '476678681450',
    projectId: 'my-recipes-28341907',
    storageBucket: 'my-recipes-28341907.appspot.com',
    iosBundleId: 'com.example.myRecipes.RunnerTests',
  );
}
